apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: ric-operator
spec:
  upstream:
    repo: catalog-workloads-oai
    package: ric-operator
    workspaceName: v5
  targets:
  - objectSelector:
      apiVersion: infra.nephio.org/v1alpha1
      kind: WorkloadCluster
    template:
      annotations:
        approval.nephio.org/policy: initial
