apiVersion: req.nephio.org/v1alpha1
kind: Dependency
metadata:
  name: cucp
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.du-example
    specializer.nephio.org/namespace: example
spec:
  packageName: oai-ran-cucp
  injectors:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
