apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: f1
  annotations:
    nephio.org/network-name: f1
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.du-example
    specializer.nephio.org/namespace: example
spec:
  networkInstance:
    name: vpc-cudu-f1
  cniType: macvlan
  attachmentType: vlan