---
apiVersion: v1
kind: Secret
metadata: # kpt-merge: /BMC_SECRET_PLACEHOLDER
  name: BMC_SECRET_PLACEHOLDER # kpt-set: ${bmc-creds-name}
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|default|BMC_SECRET_PLACEHOLDER' # kpt-set: |Secret|default|${bmc-creds-name}
type: Opaque
data:
  username: BMC_USERNAME_BASE64_PLACEHOLDER # kpt-set: ${bmc-username}
  password: BMC_PASSWORD_BASE64_PLACEHOLDER # kpt-set: ${bmc-password}