apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-cuup
spec:
  upstream:
    repo: catalog-workloads-oai
    package: pkg-example-cuup-bp
    revision: -1
  downstream:
    repo: edge
    package: oai-ran-cuup
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge
